apiVersion: v1
kind: ConfigMap
metadata:
    name: {{ include "helm.fullname" . }}-config
    labels:
        {{- include "helm.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.configs }}
    {{ $key }}: {{ $value | quote }}
{{- end }}