name: Release Build

on:
    workflow_dispatch:
      inputs:
        environment:
          description: "The environment to deploy (e.g., staging, production)"
          required: true
          default: "main - us-east-1"

jobs:
    build:
        runs-on: ubuntu-latest
        environment: ${{ github.event.inputs.environment }}
        permissions:
            id-token: write
            contents: read

        steps:
            - name: Checkout code
              uses: actions/checkout@v4.2.2
              with:
                  fetch-depth: 0

            - uses: olegtarasov/get-tag@v2.1.4
              id: tagName

            - name: Extract repository name
              id: extract_repo_name
              run: |
                  # Extract the repo name (the part after '/')
                  REPO_NAME=$(basename "${GITHUB_REPOSITORY}")
                  echo "Repository Name: $REPO_NAME"
                  
                  # Save the repo name as an environment variable
                  echo "IMAGE_NAME=$REPO_NAME" >> $GITHUB_ENV
                  
            - name: Create Image URI
              id: create_image_uri
              env:
                TAG_NAME: ${{ steps.tagName.outputs.tag }}
              run: |
                  echo "Creating image name and tag"
                  echo "IMAGE_URI=$IMAGE_NAME:$GIT_TAG_NAME" >> $GITHUB_ENV
                  echo "Image URI -> $IMAGE_NAME:$GIT_TAG_NAME"

            - name: Build Docker image
              run: |
                docker build -t ${{ env.IMAGE_URI }} .

            - name: Assume AWS workload identity
              id: assume-role
              uses: aws-actions/configure-aws-credentials@v4.0.2
              with:
                  role-to-assume: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_ROLE_NAME }}
                  aws-region: ${{ secrets.AWS_REGION }}

            - name: Log in to Amazon ECR
              uses: aws-actions/amazon-ecr-login@v2.0.1

            - name: Tag Docker image
              run: docker tag ${{ env.IMAGE_URI }} ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ env.IMAGE_URI }}

            - name: Push Docker image to ECR
              run: docker push ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ env.IMAGE_URI }}

            - name: Inject initial parameters to task definition
              env:
                EXECUTION_ROLE_ARN: arn:aws:iam::${{ secrets.AWS_ACCOUNT_ID }}:role/${{ secrets.AWS_EXEC_ROLE_NAME }}
                CPU: 256
                MEMORY: 512
              run: pipelineScripts/inject-into-task-def.sh $CPU $MEMORY $EXECUTION_ROLE_ARN

            - name: Render Amazon ECS task definition
              id: render-web-container
              uses: aws-actions/amazon-ecs-render-task-definition@v1.6.2
              with:
                task-definition: task-definition-updated.json
                task-definition-family: discord-bot
                container-name: mr-bot
                image: ${{ secrets.AWS_ACCOUNT_ID }}.dkr.ecr.${{ secrets.AWS_REGION }}.amazonaws.com/${{ env.IMAGE_URI }}
                environment-variables: |
                  LOG_LEVEL=info
                  LOGGING_FORMAT=json
                  DISCORD_GUILD_ID=${{ env.DISCORD_GUILD_ID }}}
                  FOOTER_MSG="© 2024 - Made with discord.py"
                  AUTHOR="${{ env.AUTHOR }}"
                secrets: "DISCORD_TOKEN=arn:aws:ssm:${{ secrets.AWS_REGION }}:${{ secrets.AWS_ACCOUNT_ID }}:parameter/${{ secrets.SSM_DISCORD_TOKEN_NAME }}"
                log-configuration-log-driver: awslogs
                log-configuration-options: |
                  awslogs-create-group=true
                  awslogs-group=/ecs/mrbot
                  awslogs-region=${{ secrets.AWS_REGION }}
                  awslogs-stream-prefix=ecs
        
            - name: Deploy to Amazon ECS service
              uses: aws-actions/amazon-ecs-deploy-task-definition@v2
              with:
                task-definition: ${{ steps.render-web-container.outputs.task-definition }}
                service: ${{ secrets.AWS_ECS_SERVICE_NAME }}
                cluster: ${{ secrets.AWS_ECS_CLUSTER_NAME }}
                wait-for-service-stability: true
                